spring:
  datasource:
    driverClassName:  org.postgresql.Driver
      platform: postgres
    url: =${JDBC_DATABASE_URL:}
    username: =${JDBC_DATABASE_USERNAME:}
    password: =${JDBC_DATABASE_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

        server:
          error:
            whitelabel:
              enabled: false

  #sql:
    #init:
      #mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    database-platform: postgres
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name:

